### ISSUE TITLE
Upgrade to the code

### ISSUE THREAD

**Issue by JunaidLone17** [IshfaqKhawaja/Insta-BOT#1]
instead of using this
`browser = webdriver.Chrome()` and Getting a potential Path to webdriver error use
`from webdriver_manager.chrome import ChromeDriverManager
browser = webdriver.Chrome(ChromeDriverManager().install())` to resolve any errors related to path variable

**Comment by IshfaqKhawaja** [comment]
Do it

**Comment by IshfaqKhawaja** [comment]
Done
